### ISSUE TITLE
when panel option page, event not working

### ISSUE THREAD

**Issue by SMARTINFRALAB** [ACE-IoT-Solutions/ace-svg-react#56] opened 2024-04-28 05:45 UTC
![image](https://github.com/ACE-IoT-Solutions/ace-svg-react/assets/161649556/09436caf-2987-445a-a85c-75df68c441a0)

Event not working.

I tested with grafana 10.3.3 but not working.

options.tsx , variable "this" is undefined 
![image](https://github.com/ACE-IoT-Solutions/ace-svg-react/assets/161649556/855179f8-c0dc-4c1f-9d62-4f587c4bb5f0)

**Comment by nicfv** [comment] 2024-05-01 16:12
Sorry to hear that you are experiencing a bug in the plugin. Can you please attach a file containing the dashboard JSON data?

![image](https://github.com/ACE-IoT-Solutions/ace-svg-react/assets/24358775/75e3fde1-2a0d-446c-acd0-6ae787f2153d)

![image](https://github.com/ACE-IoT-Solutions/ace-svg-react/assets/24358775/8bdaaf26-764f-4da9-af8a-201a09c6462f)

**Comment by nicfv** [comment] 2024-05-02 05:01
Seems like this might be the cause of the error: https://stackoverflow.com/questions/33973648/react-this-is-undefined-inside-a-component-function

Testing out code in #58 which should close this issue. Thank you for your patience!

**Closed** 2024-05-02 05:41 UTC
Labels: bug

**Comment by nicfv** [comment] 2024-05-02 05:46
ACE.SVG version 0.1.4 is awaiting review to be published on the Grafana plugin marketplace. Please try updating when it is available, and feel free to open a new issue if there are any problems.
